"""Domain models for reports, semantic models and diff results.

All models are immutable Pydantic models. Collections are tuples so that a
model can be hashed, compared and serialised deterministically. The models
live in ``report``, ``semantic``, ``data`` and ``diff``; this module
re-exports them all.
"""

from pbi_report_validator.domain.base import DomainModel
from pbi_report_validator.domain.data import (
    CellValue,
    DataStatus,
    DataSummary,
    DaxQuery,
    QueryResult,
    Tolerance,
    UnsupportedQuery,
)
from pbi_report_validator.domain.diff import (
    SCHEMA_VERSION,
    Category,
    ChangeKind,
    DataComparison,
    DiffResult,
    Finding,
    ItemStatus,
    MatchMethod,
    PageMatch,
    PageView,
    ReportMatch,
    VisualMatch,
    VisualView,
)
from pbi_report_validator.domain.report import (
    AllCondition,
    BinaryCondition,
    ComparisonCondition,
    Condition,
    FieldKind,
    FieldRef,
    Filter,
    FilterLevel,
    InCondition,
    LiteralKind,
    LiteralValue,
    NotCondition,
    Page,
    ParseIssue,
    Position,
    Projection,
    Report,
    SlicerState,
    Visual,
)
from pbi_report_validator.domain.semantic import (
    Column,
    Measure,
    SemanticModel,
    Table,
)

__all__ = [
    "SCHEMA_VERSION",
    "AllCondition",
    "BinaryCondition",
    "Category",
    "CellValue",
    "ChangeKind",
    "Column",
    "ComparisonCondition",
    "Condition",
    "DataComparison",
    "DataStatus",
    "DataSummary",
    "DaxQuery",
    "DiffResult",
    "DomainModel",
    "FieldKind",
    "FieldRef",
    "Filter",
    "FilterLevel",
    "Finding",
    "InCondition",
    "ItemStatus",
    "LiteralKind",
    "LiteralValue",
    "MatchMethod",
    "Measure",
    "NotCondition",
    "Page",
    "PageMatch",
    "PageView",
    "ParseIssue",
    "Position",
    "Projection",
    "QueryResult",
    "Report",
    "ReportMatch",
    "SemanticModel",
    "SlicerState",
    "Table",
    "Tolerance",
    "UnsupportedQuery",
    "Visual",
    "VisualMatch",
    "VisualView",
]
